=begin
#MilMove Prime V3 API

#The Prime V3 API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `/prime/v3/`. 

The version of the OpenAPI document: 0.0.1
Contact: milmove-developers@caci.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  # A personally procured move is a type of shipment that a service member moves themselves.
  class PPMShipmentV3
    # The primary unique identifier of this PPM shipment
    attr_accessor :id

    # The id of the parent MTOShipment record
    attr_accessor :shipment_id

    # The timestamp of when the PPM shipment was created (UTC)
    attr_accessor :created_at

    # The timestamp of when a property of this object was last updated (UTC)
    attr_accessor :updated_at

    attr_accessor :status

    # Date the customer expects to begin moving from their origin. 
    attr_accessor :expected_departure_date

    # The actual start date of when the PPM shipment left the origin.
    attr_accessor :actual_move_date

    # The timestamp of when the customer submitted their PPM documentation to the counselor for review.
    attr_accessor :submitted_at

    # The timestamp of when the Service Counselor has reviewed all of the closeout documents.
    attr_accessor :reviewed_at

    # The timestamp of when the shipment was approved and the service member can begin their move.
    attr_accessor :approved_at

    attr_accessor :pickup_address

    attr_accessor :secondary_pickup_address

    attr_accessor :has_secondary_pickup_address

    # The actual postal code where the PPM shipment started. To be filled once the customer has moved the shipment. 
    attr_accessor :actual_pickup_postal_code

    attr_accessor :destination_address

    attr_accessor :secondary_destination_address

    attr_accessor :has_secondary_destination_address

    # The actual postal code where the PPM shipment ended. To be filled once the customer has moved the shipment. 
    attr_accessor :actual_destination_postal_code

    # Captures whether some or all of the PPM shipment will require temporary storage at the origin or destination.  Must be set to `true` when providing `sitLocation`, `sitEstimatedWeight`, `sitEstimatedEntryDate`, and `sitEstimatedDepartureDate` values to calculate the `sitEstimatedCost`. 
    attr_accessor :sit_expected

    # The estimated weight of the PPM shipment goods being moved in pounds.
    attr_accessor :estimated_weight

    # Indicates whether PPM shipment has pro gear for themselves or their spouse. 
    attr_accessor :has_pro_gear

    # The estimated weight of the pro-gear being moved belonging to the service member in pounds.
    attr_accessor :pro_gear_weight

    # The estimated weight of the pro-gear being moved belonging to a spouse in pounds.
    attr_accessor :spouse_pro_gear_weight

    # The estimated amount the government will pay the service member to move their belongings based on the moving date, locations, and shipment weight.
    attr_accessor :estimated_incentive

    # Indicates whether an advance has been requested for the PPM shipment. 
    attr_accessor :has_requested_advance

    # The amount requested as an advance by the service member, up to a maximum percentage of the estimated incentive. 
    attr_accessor :advance_amount_requested

    # Indicates whether an advance was received for the PPM shipment. 
    attr_accessor :has_received_advance

    # The amount received for an advance, or null if no advance is received. 
    attr_accessor :advance_amount_received

    attr_accessor :sit_location

    # The estimated weight of the goods being put into storage in pounds.
    attr_accessor :sit_estimated_weight

    # The date that goods will first enter the storage location.
    attr_accessor :sit_estimated_entry_date

    # The date that goods will exit the storage location.
    attr_accessor :sit_estimated_departure_date

    # The estimated amount that the government will pay the service member to put their goods into storage. This estimated storage cost is separate from the estimated incentive.
    attr_accessor :sit_estimated_cost

    # A hash unique to this shipment that should be used as the \"If-Match\" header for any updates.
    attr_accessor :e_tag

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'shipment_id' => :'shipmentId',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt',
        :'status' => :'status',
        :'expected_departure_date' => :'expectedDepartureDate',
        :'actual_move_date' => :'actualMoveDate',
        :'submitted_at' => :'submittedAt',
        :'reviewed_at' => :'reviewedAt',
        :'approved_at' => :'approvedAt',
        :'pickup_address' => :'pickupAddress',
        :'secondary_pickup_address' => :'secondaryPickupAddress',
        :'has_secondary_pickup_address' => :'hasSecondaryPickupAddress',
        :'actual_pickup_postal_code' => :'actualPickupPostalCode',
        :'destination_address' => :'destinationAddress',
        :'secondary_destination_address' => :'secondaryDestinationAddress',
        :'has_secondary_destination_address' => :'hasSecondaryDestinationAddress',
        :'actual_destination_postal_code' => :'actualDestinationPostalCode',
        :'sit_expected' => :'sitExpected',
        :'estimated_weight' => :'estimatedWeight',
        :'has_pro_gear' => :'hasProGear',
        :'pro_gear_weight' => :'proGearWeight',
        :'spouse_pro_gear_weight' => :'spouseProGearWeight',
        :'estimated_incentive' => :'estimatedIncentive',
        :'has_requested_advance' => :'hasRequestedAdvance',
        :'advance_amount_requested' => :'advanceAmountRequested',
        :'has_received_advance' => :'hasReceivedAdvance',
        :'advance_amount_received' => :'advanceAmountReceived',
        :'sit_location' => :'sitLocation',
        :'sit_estimated_weight' => :'sitEstimatedWeight',
        :'sit_estimated_entry_date' => :'sitEstimatedEntryDate',
        :'sit_estimated_departure_date' => :'sitEstimatedDepartureDate',
        :'sit_estimated_cost' => :'sitEstimatedCost',
        :'e_tag' => :'eTag'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'shipment_id' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'status' => :'PPMShipmentStatusV3',
        :'expected_departure_date' => :'Date',
        :'actual_move_date' => :'Date',
        :'submitted_at' => :'Time',
        :'reviewed_at' => :'Time',
        :'approved_at' => :'Time',
        :'pickup_address' => :'AddressV3',
        :'secondary_pickup_address' => :'AddressV3',
        :'has_secondary_pickup_address' => :'Boolean',
        :'actual_pickup_postal_code' => :'String',
        :'destination_address' => :'AddressV3',
        :'secondary_destination_address' => :'AddressV3',
        :'has_secondary_destination_address' => :'Boolean',
        :'actual_destination_postal_code' => :'String',
        :'sit_expected' => :'Boolean',
        :'estimated_weight' => :'Integer',
        :'has_pro_gear' => :'Boolean',
        :'pro_gear_weight' => :'Integer',
        :'spouse_pro_gear_weight' => :'Integer',
        :'estimated_incentive' => :'Integer',
        :'has_requested_advance' => :'Boolean',
        :'advance_amount_requested' => :'Integer',
        :'has_received_advance' => :'Boolean',
        :'advance_amount_received' => :'Integer',
        :'sit_location' => :'SITLocationTypeV3',
        :'sit_estimated_weight' => :'Integer',
        :'sit_estimated_entry_date' => :'Date',
        :'sit_estimated_departure_date' => :'Date',
        :'sit_estimated_cost' => :'Integer',
        :'e_tag' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'actual_move_date',
        :'submitted_at',
        :'reviewed_at',
        :'approved_at',
        :'has_secondary_pickup_address',
        :'actual_pickup_postal_code',
        :'has_secondary_destination_address',
        :'actual_destination_postal_code',
        :'estimated_weight',
        :'has_pro_gear',
        :'pro_gear_weight',
        :'spouse_pro_gear_weight',
        :'estimated_incentive',
        :'has_requested_advance',
        :'advance_amount_requested',
        :'has_received_advance',
        :'advance_amount_received',
        :'sit_estimated_weight',
        :'sit_estimated_entry_date',
        :'sit_estimated_departure_date',
        :'sit_estimated_cost',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PPMShipmentV3` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PPMShipmentV3`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'shipment_id')
        self.shipment_id = attributes[:'shipment_id']
      else
        self.shipment_id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'expected_departure_date')
        self.expected_departure_date = attributes[:'expected_departure_date']
      else
        self.expected_departure_date = nil
      end

      if attributes.key?(:'actual_move_date')
        self.actual_move_date = attributes[:'actual_move_date']
      end

      if attributes.key?(:'submitted_at')
        self.submitted_at = attributes[:'submitted_at']
      end

      if attributes.key?(:'reviewed_at')
        self.reviewed_at = attributes[:'reviewed_at']
      end

      if attributes.key?(:'approved_at')
        self.approved_at = attributes[:'approved_at']
      end

      if attributes.key?(:'pickup_address')
        self.pickup_address = attributes[:'pickup_address']
      else
        self.pickup_address = nil
      end

      if attributes.key?(:'secondary_pickup_address')
        self.secondary_pickup_address = attributes[:'secondary_pickup_address']
      end

      if attributes.key?(:'has_secondary_pickup_address')
        self.has_secondary_pickup_address = attributes[:'has_secondary_pickup_address']
      end

      if attributes.key?(:'actual_pickup_postal_code')
        self.actual_pickup_postal_code = attributes[:'actual_pickup_postal_code']
      end

      if attributes.key?(:'destination_address')
        self.destination_address = attributes[:'destination_address']
      else
        self.destination_address = nil
      end

      if attributes.key?(:'secondary_destination_address')
        self.secondary_destination_address = attributes[:'secondary_destination_address']
      end

      if attributes.key?(:'has_secondary_destination_address')
        self.has_secondary_destination_address = attributes[:'has_secondary_destination_address']
      end

      if attributes.key?(:'actual_destination_postal_code')
        self.actual_destination_postal_code = attributes[:'actual_destination_postal_code']
      end

      if attributes.key?(:'sit_expected')
        self.sit_expected = attributes[:'sit_expected']
      else
        self.sit_expected = nil
      end

      if attributes.key?(:'estimated_weight')
        self.estimated_weight = attributes[:'estimated_weight']
      end

      if attributes.key?(:'has_pro_gear')
        self.has_pro_gear = attributes[:'has_pro_gear']
      end

      if attributes.key?(:'pro_gear_weight')
        self.pro_gear_weight = attributes[:'pro_gear_weight']
      end

      if attributes.key?(:'spouse_pro_gear_weight')
        self.spouse_pro_gear_weight = attributes[:'spouse_pro_gear_weight']
      end

      if attributes.key?(:'estimated_incentive')
        self.estimated_incentive = attributes[:'estimated_incentive']
      end

      if attributes.key?(:'has_requested_advance')
        self.has_requested_advance = attributes[:'has_requested_advance']
      end

      if attributes.key?(:'advance_amount_requested')
        self.advance_amount_requested = attributes[:'advance_amount_requested']
      end

      if attributes.key?(:'has_received_advance')
        self.has_received_advance = attributes[:'has_received_advance']
      end

      if attributes.key?(:'advance_amount_received')
        self.advance_amount_received = attributes[:'advance_amount_received']
      end

      if attributes.key?(:'sit_location')
        if (value = attributes[:'sit_location']).is_a?(Hash)
          self.sit_location = value
        end
        self.sit_location = attributes[:'sit_location']
      end

      if attributes.key?(:'sit_estimated_weight')
        self.sit_estimated_weight = attributes[:'sit_estimated_weight']
      end

      if attributes.key?(:'sit_estimated_entry_date')
        self.sit_estimated_entry_date = attributes[:'sit_estimated_entry_date']
      end

      if attributes.key?(:'sit_estimated_departure_date')
        self.sit_estimated_departure_date = attributes[:'sit_estimated_departure_date']
      end

      if attributes.key?(:'sit_estimated_cost')
        self.sit_estimated_cost = attributes[:'sit_estimated_cost']
      end

      if attributes.key?(:'e_tag')
        self.e_tag = attributes[:'e_tag']
      else
        self.e_tag = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @shipment_id.nil?
        invalid_properties.push('invalid value for "shipment_id", shipment_id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @expected_departure_date.nil?
        invalid_properties.push('invalid value for "expected_departure_date", expected_departure_date cannot be nil.')
      end

      if @pickup_address.nil?
        invalid_properties.push('invalid value for "pickup_address", pickup_address cannot be nil.')
      end

      pattern = Regexp.new(/^(\d{5})$/)
      if !@actual_pickup_postal_code.nil? && @actual_pickup_postal_code !~ pattern
        invalid_properties.push("invalid value for \"actual_pickup_postal_code\", must conform to the pattern #{pattern}.")
      end

      if @destination_address.nil?
        invalid_properties.push('invalid value for "destination_address", destination_address cannot be nil.')
      end

      pattern = Regexp.new(/^(\d{5})$/)
      if !@actual_destination_postal_code.nil? && @actual_destination_postal_code !~ pattern
        invalid_properties.push("invalid value for \"actual_destination_postal_code\", must conform to the pattern #{pattern}.")
      end

      if @sit_expected.nil?
        invalid_properties.push('invalid value for "sit_expected", sit_expected cannot be nil.')
      end

      if @e_tag.nil?
        invalid_properties.push('invalid value for "e_tag", e_tag cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @shipment_id.nil?
      return false if @created_at.nil?
      return false if @status.nil?
      return false if @expected_departure_date.nil?
      return false if @pickup_address.nil?
      return false if !@actual_pickup_postal_code.nil? && @actual_pickup_postal_code !~ Regexp.new(/^(\d{5})$/)
      return false if @destination_address.nil?
      return false if !@actual_destination_postal_code.nil? && @actual_destination_postal_code !~ Regexp.new(/^(\d{5})$/)
      return false if @sit_expected.nil?
      return false if @e_tag.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] actual_pickup_postal_code Value to be assigned
    def actual_pickup_postal_code=(actual_pickup_postal_code)
      pattern = Regexp.new(/^(\d{5})$/)
      if !actual_pickup_postal_code.nil? && actual_pickup_postal_code !~ pattern
        fail ArgumentError, "invalid value for \"actual_pickup_postal_code\", must conform to the pattern #{pattern}."
      end

      @actual_pickup_postal_code = actual_pickup_postal_code
    end

    # Custom attribute writer method with validation
    # @param [Object] actual_destination_postal_code Value to be assigned
    def actual_destination_postal_code=(actual_destination_postal_code)
      pattern = Regexp.new(/^(\d{5})$/)
      if !actual_destination_postal_code.nil? && actual_destination_postal_code !~ pattern
        fail ArgumentError, "invalid value for \"actual_destination_postal_code\", must conform to the pattern #{pattern}."
      end

      @actual_destination_postal_code = actual_destination_postal_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          shipment_id == o.shipment_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          status == o.status &&
          expected_departure_date == o.expected_departure_date &&
          actual_move_date == o.actual_move_date &&
          submitted_at == o.submitted_at &&
          reviewed_at == o.reviewed_at &&
          approved_at == o.approved_at &&
          pickup_address == o.pickup_address &&
          secondary_pickup_address == o.secondary_pickup_address &&
          has_secondary_pickup_address == o.has_secondary_pickup_address &&
          actual_pickup_postal_code == o.actual_pickup_postal_code &&
          destination_address == o.destination_address &&
          secondary_destination_address == o.secondary_destination_address &&
          has_secondary_destination_address == o.has_secondary_destination_address &&
          actual_destination_postal_code == o.actual_destination_postal_code &&
          sit_expected == o.sit_expected &&
          estimated_weight == o.estimated_weight &&
          has_pro_gear == o.has_pro_gear &&
          pro_gear_weight == o.pro_gear_weight &&
          spouse_pro_gear_weight == o.spouse_pro_gear_weight &&
          estimated_incentive == o.estimated_incentive &&
          has_requested_advance == o.has_requested_advance &&
          advance_amount_requested == o.advance_amount_requested &&
          has_received_advance == o.has_received_advance &&
          advance_amount_received == o.advance_amount_received &&
          sit_location == o.sit_location &&
          sit_estimated_weight == o.sit_estimated_weight &&
          sit_estimated_entry_date == o.sit_estimated_entry_date &&
          sit_estimated_departure_date == o.sit_estimated_departure_date &&
          sit_estimated_cost == o.sit_estimated_cost &&
          e_tag == o.e_tag
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, shipment_id, created_at, updated_at, status, expected_departure_date, actual_move_date, submitted_at, reviewed_at, approved_at, pickup_address, secondary_pickup_address, has_secondary_pickup_address, actual_pickup_postal_code, destination_address, secondary_destination_address, has_secondary_destination_address, actual_destination_postal_code, sit_expected, estimated_weight, has_pro_gear, pro_gear_weight, spouse_pro_gear_weight, estimated_incentive, has_requested_advance, advance_amount_requested, has_received_advance, advance_amount_received, sit_location, sit_estimated_weight, sit_estimated_entry_date, sit_estimated_departure_date, sit_estimated_cost, e_tag].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
