/*
MilMove Prime API

Testing MtoServiceItemAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_MtoServiceItemAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MtoServiceItemAPIService CreateMTOServiceItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MtoServiceItemAPI.CreateMTOServiceItem(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MtoServiceItemAPIService CreateServiceRequestDocumentUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mtoServiceItemID string

		resp, httpRes, err := apiClient.MtoServiceItemAPI.CreateServiceRequestDocumentUpload(context.Background(), mtoServiceItemID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MtoServiceItemAPIService UpdateMTOServiceItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mtoServiceItemID string

		resp, httpRes, err := apiClient.MtoServiceItemAPI.UpdateMTOServiceItem(context.Background(), mtoServiceItemID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
