/*
MilMove Prime V2 API

The Prime V2 API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `/prime/v2/`. 

API version: 0.0.1
Contact: milmove-developers@caci.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShipmentAddressUpdateV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShipmentAddressUpdateV2{}

// ShipmentAddressUpdateV2 This represents a destination address change request made by the Prime that is either auto-approved or requires review if the pricing criteria has changed. If criteria has changed, then it must be approved or rejected by a TOO. 
type ShipmentAddressUpdateV2 struct {
	Id string `json:"id"`
	// The reason there is an address change.
	ContractorRemarks string `json:"contractorRemarks"`
	// The TOO comment on approval or rejection.
	OfficeRemarks NullableString `json:"officeRemarks,omitempty"`
	Status ShipmentAddressUpdateStatusV2V2 `json:"status"`
	ShipmentID string `json:"shipmentID"`
	OriginalAddress AddressV2V2 `json:"originalAddress"`
	NewAddress AddressV2V2 `json:"newAddress"`
	SitOriginalAddress *AddressV2V2 `json:"sitOriginalAddress,omitempty"`
	// The distance between the original SIT address and the previous/old destination address of shipment
	OldSitDistanceBetween *int32 `json:"oldSitDistanceBetween,omitempty"`
	// The distance between the original SIT address and requested new destination address of shipment
	NewSitDistanceBetween *int32 `json:"newSitDistanceBetween,omitempty"`
}

type _ShipmentAddressUpdateV2 ShipmentAddressUpdateV2

// NewShipmentAddressUpdateV2 instantiates a new ShipmentAddressUpdateV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipmentAddressUpdateV2(id string, contractorRemarks string, status ShipmentAddressUpdateStatusV2V2, shipmentID string, originalAddress AddressV2V2, newAddress AddressV2V2) *ShipmentAddressUpdateV2 {
	this := ShipmentAddressUpdateV2{}
	this.Id = id
	this.ContractorRemarks = contractorRemarks
	this.Status = status
	this.ShipmentID = shipmentID
	this.OriginalAddress = originalAddress
	this.NewAddress = newAddress
	return &this
}

// NewShipmentAddressUpdateV2WithDefaults instantiates a new ShipmentAddressUpdateV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipmentAddressUpdateV2WithDefaults() *ShipmentAddressUpdateV2 {
	this := ShipmentAddressUpdateV2{}
	return &this
}

// GetId returns the Id field value
func (o *ShipmentAddressUpdateV2) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ShipmentAddressUpdateV2) SetId(v string) {
	o.Id = v
}

// GetContractorRemarks returns the ContractorRemarks field value
func (o *ShipmentAddressUpdateV2) GetContractorRemarks() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractorRemarks
}

// GetContractorRemarksOk returns a tuple with the ContractorRemarks field value
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetContractorRemarksOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractorRemarks, true
}

// SetContractorRemarks sets field value
func (o *ShipmentAddressUpdateV2) SetContractorRemarks(v string) {
	o.ContractorRemarks = v
}

// GetOfficeRemarks returns the OfficeRemarks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShipmentAddressUpdateV2) GetOfficeRemarks() string {
	if o == nil || IsNil(o.OfficeRemarks.Get()) {
		var ret string
		return ret
	}
	return *o.OfficeRemarks.Get()
}

// GetOfficeRemarksOk returns a tuple with the OfficeRemarks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShipmentAddressUpdateV2) GetOfficeRemarksOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OfficeRemarks.Get(), o.OfficeRemarks.IsSet()
}

// HasOfficeRemarks returns a boolean if a field has been set.
func (o *ShipmentAddressUpdateV2) HasOfficeRemarks() bool {
	if o != nil && o.OfficeRemarks.IsSet() {
		return true
	}

	return false
}

// SetOfficeRemarks gets a reference to the given NullableString and assigns it to the OfficeRemarks field.
func (o *ShipmentAddressUpdateV2) SetOfficeRemarks(v string) {
	o.OfficeRemarks.Set(&v)
}
// SetOfficeRemarksNil sets the value for OfficeRemarks to be an explicit nil
func (o *ShipmentAddressUpdateV2) SetOfficeRemarksNil() {
	o.OfficeRemarks.Set(nil)
}

// UnsetOfficeRemarks ensures that no value is present for OfficeRemarks, not even an explicit nil
func (o *ShipmentAddressUpdateV2) UnsetOfficeRemarks() {
	o.OfficeRemarks.Unset()
}

// GetStatus returns the Status field value
func (o *ShipmentAddressUpdateV2) GetStatus() ShipmentAddressUpdateStatusV2V2 {
	if o == nil {
		var ret ShipmentAddressUpdateStatusV2V2
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetStatusOk() (*ShipmentAddressUpdateStatusV2V2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ShipmentAddressUpdateV2) SetStatus(v ShipmentAddressUpdateStatusV2V2) {
	o.Status = v
}

// GetShipmentID returns the ShipmentID field value
func (o *ShipmentAddressUpdateV2) GetShipmentID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipmentID
}

// GetShipmentIDOk returns a tuple with the ShipmentID field value
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetShipmentIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentID, true
}

// SetShipmentID sets field value
func (o *ShipmentAddressUpdateV2) SetShipmentID(v string) {
	o.ShipmentID = v
}

// GetOriginalAddress returns the OriginalAddress field value
func (o *ShipmentAddressUpdateV2) GetOriginalAddress() AddressV2V2 {
	if o == nil {
		var ret AddressV2V2
		return ret
	}

	return o.OriginalAddress
}

// GetOriginalAddressOk returns a tuple with the OriginalAddress field value
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetOriginalAddressOk() (*AddressV2V2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalAddress, true
}

// SetOriginalAddress sets field value
func (o *ShipmentAddressUpdateV2) SetOriginalAddress(v AddressV2V2) {
	o.OriginalAddress = v
}

// GetNewAddress returns the NewAddress field value
func (o *ShipmentAddressUpdateV2) GetNewAddress() AddressV2V2 {
	if o == nil {
		var ret AddressV2V2
		return ret
	}

	return o.NewAddress
}

// GetNewAddressOk returns a tuple with the NewAddress field value
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetNewAddressOk() (*AddressV2V2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewAddress, true
}

// SetNewAddress sets field value
func (o *ShipmentAddressUpdateV2) SetNewAddress(v AddressV2V2) {
	o.NewAddress = v
}

// GetSitOriginalAddress returns the SitOriginalAddress field value if set, zero value otherwise.
func (o *ShipmentAddressUpdateV2) GetSitOriginalAddress() AddressV2V2 {
	if o == nil || IsNil(o.SitOriginalAddress) {
		var ret AddressV2V2
		return ret
	}
	return *o.SitOriginalAddress
}

// GetSitOriginalAddressOk returns a tuple with the SitOriginalAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetSitOriginalAddressOk() (*AddressV2V2, bool) {
	if o == nil || IsNil(o.SitOriginalAddress) {
		return nil, false
	}
	return o.SitOriginalAddress, true
}

// HasSitOriginalAddress returns a boolean if a field has been set.
func (o *ShipmentAddressUpdateV2) HasSitOriginalAddress() bool {
	if o != nil && !IsNil(o.SitOriginalAddress) {
		return true
	}

	return false
}

// SetSitOriginalAddress gets a reference to the given AddressV2V2 and assigns it to the SitOriginalAddress field.
func (o *ShipmentAddressUpdateV2) SetSitOriginalAddress(v AddressV2V2) {
	o.SitOriginalAddress = &v
}

// GetOldSitDistanceBetween returns the OldSitDistanceBetween field value if set, zero value otherwise.
func (o *ShipmentAddressUpdateV2) GetOldSitDistanceBetween() int32 {
	if o == nil || IsNil(o.OldSitDistanceBetween) {
		var ret int32
		return ret
	}
	return *o.OldSitDistanceBetween
}

// GetOldSitDistanceBetweenOk returns a tuple with the OldSitDistanceBetween field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetOldSitDistanceBetweenOk() (*int32, bool) {
	if o == nil || IsNil(o.OldSitDistanceBetween) {
		return nil, false
	}
	return o.OldSitDistanceBetween, true
}

// HasOldSitDistanceBetween returns a boolean if a field has been set.
func (o *ShipmentAddressUpdateV2) HasOldSitDistanceBetween() bool {
	if o != nil && !IsNil(o.OldSitDistanceBetween) {
		return true
	}

	return false
}

// SetOldSitDistanceBetween gets a reference to the given int32 and assigns it to the OldSitDistanceBetween field.
func (o *ShipmentAddressUpdateV2) SetOldSitDistanceBetween(v int32) {
	o.OldSitDistanceBetween = &v
}

// GetNewSitDistanceBetween returns the NewSitDistanceBetween field value if set, zero value otherwise.
func (o *ShipmentAddressUpdateV2) GetNewSitDistanceBetween() int32 {
	if o == nil || IsNil(o.NewSitDistanceBetween) {
		var ret int32
		return ret
	}
	return *o.NewSitDistanceBetween
}

// GetNewSitDistanceBetweenOk returns a tuple with the NewSitDistanceBetween field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentAddressUpdateV2) GetNewSitDistanceBetweenOk() (*int32, bool) {
	if o == nil || IsNil(o.NewSitDistanceBetween) {
		return nil, false
	}
	return o.NewSitDistanceBetween, true
}

// HasNewSitDistanceBetween returns a boolean if a field has been set.
func (o *ShipmentAddressUpdateV2) HasNewSitDistanceBetween() bool {
	if o != nil && !IsNil(o.NewSitDistanceBetween) {
		return true
	}

	return false
}

// SetNewSitDistanceBetween gets a reference to the given int32 and assigns it to the NewSitDistanceBetween field.
func (o *ShipmentAddressUpdateV2) SetNewSitDistanceBetween(v int32) {
	o.NewSitDistanceBetween = &v
}

func (o ShipmentAddressUpdateV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShipmentAddressUpdateV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["contractorRemarks"] = o.ContractorRemarks
	if o.OfficeRemarks.IsSet() {
		toSerialize["officeRemarks"] = o.OfficeRemarks.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["shipmentID"] = o.ShipmentID
	toSerialize["originalAddress"] = o.OriginalAddress
	toSerialize["newAddress"] = o.NewAddress
	if !IsNil(o.SitOriginalAddress) {
		toSerialize["sitOriginalAddress"] = o.SitOriginalAddress
	}
	if !IsNil(o.OldSitDistanceBetween) {
		toSerialize["oldSitDistanceBetween"] = o.OldSitDistanceBetween
	}
	if !IsNil(o.NewSitDistanceBetween) {
		toSerialize["newSitDistanceBetween"] = o.NewSitDistanceBetween
	}
	return toSerialize, nil
}

func (o *ShipmentAddressUpdateV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"contractorRemarks",
		"status",
		"shipmentID",
		"originalAddress",
		"newAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShipmentAddressUpdateV2 := _ShipmentAddressUpdateV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShipmentAddressUpdateV2)

	if err != nil {
		return err
	}

	*o = ShipmentAddressUpdateV2(varShipmentAddressUpdateV2)

	return err
}

type NullableShipmentAddressUpdateV2 struct {
	value *ShipmentAddressUpdateV2
	isSet bool
}

func (v NullableShipmentAddressUpdateV2) Get() *ShipmentAddressUpdateV2 {
	return v.value
}

func (v *NullableShipmentAddressUpdateV2) Set(val *ShipmentAddressUpdateV2) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentAddressUpdateV2) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentAddressUpdateV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentAddressUpdateV2(val *ShipmentAddressUpdateV2) *NullableShipmentAddressUpdateV2 {
	return &NullableShipmentAddressUpdateV2{value: val, isSet: true}
}

func (v NullableShipmentAddressUpdateV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentAddressUpdateV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


