/*
MilMove Prime API

The Prime API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `/prime/v1/`. 

API version: 0.0.1
Contact: milmove-developers@caci.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MTOServiceItemDestSIT type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MTOServiceItemDestSIT{}

// MTOServiceItemDestSIT Describes a domestic destination SIT service item. Subtype of a MTOServiceItem.
type MTOServiceItemDestSIT struct {
	MTOServiceItem
	// Service code allowed for this model type.
	ReServiceCode string `json:"reServiceCode"`
	// Date of attempted contact by the prime corresponding to `timeMilitary1`.
	DateOfContact1 NullableString `json:"dateOfContact1,omitempty"`
	// Date of attempted contact by the prime corresponding to `timeMilitary2`.
	DateOfContact2 NullableString `json:"dateOfContact2,omitempty"`
	// Time of attempted contact corresponding to `dateOfContact1`, in military format.
	TimeMilitary1 NullableString `json:"timeMilitary1,omitempty" validate:"regexp=\\\\d{4}Z"`
	// Time of attempted contact corresponding to `dateOfContact2`, in military format.
	TimeMilitary2 NullableString `json:"timeMilitary2,omitempty" validate:"regexp=\\\\d{4}Z"`
	// First available date that Prime can deliver SIT service item.
	FirstAvailableDeliveryDate1 NullableString `json:"firstAvailableDeliveryDate1,omitempty"`
	// Second available date that Prime can deliver SIT service item.
	FirstAvailableDeliveryDate2 NullableString `json:"firstAvailableDeliveryDate2,omitempty"`
	// Entry date for the SIT
	SitEntryDate string `json:"sitEntryDate"`
	// Departure date for SIT. This is the end date of the SIT at either origin or destination. This is optional as it can be updated using the UpdateMTOServiceItemSIT modelType at a later date.
	SitDepartureDate NullableString `json:"sitDepartureDate,omitempty"`
	SitDestinationFinalAddress *Address `json:"sitDestinationFinalAddress,omitempty"`
	// The reason item has been placed in SIT. 
	Reason NullableString `json:"reason"`
	// A list of updates to a SIT service item address.
	SitAddressUpdates []SitAddressUpdate `json:"sitAddressUpdates,omitempty"`
	// Date when the customer has requested delivery out of SIT.
	SitRequestedDelivery NullableString `json:"sitRequestedDelivery,omitempty"`
	// Date when the customer contacted the prime for a delivery out of SIT.
	SitCustomerContacted NullableString `json:"sitCustomerContacted,omitempty"`
}

type _MTOServiceItemDestSIT MTOServiceItemDestSIT

// NewMTOServiceItemDestSIT instantiates a new MTOServiceItemDestSIT object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMTOServiceItemDestSIT(reServiceCode string, sitEntryDate string, reason NullableString, moveTaskOrderID string, modelType MTOServiceItemModelType) *MTOServiceItemDestSIT {
	this := MTOServiceItemDestSIT{}
	this.MoveTaskOrderID = moveTaskOrderID
	this.ModelType = modelType
	this.ReServiceCode = reServiceCode
	this.SitEntryDate = sitEntryDate
	this.Reason = reason
	return &this
}

// NewMTOServiceItemDestSITWithDefaults instantiates a new MTOServiceItemDestSIT object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMTOServiceItemDestSITWithDefaults() *MTOServiceItemDestSIT {
	this := MTOServiceItemDestSIT{}
	return &this
}

// GetReServiceCode returns the ReServiceCode field value
func (o *MTOServiceItemDestSIT) GetReServiceCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReServiceCode
}

// GetReServiceCodeOk returns a tuple with the ReServiceCode field value
// and a boolean to check if the value has been set.
func (o *MTOServiceItemDestSIT) GetReServiceCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReServiceCode, true
}

// SetReServiceCode sets field value
func (o *MTOServiceItemDestSIT) SetReServiceCode(v string) {
	o.ReServiceCode = v
}

// GetDateOfContact1 returns the DateOfContact1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetDateOfContact1() string {
	if o == nil || IsNil(o.DateOfContact1.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfContact1.Get()
}

// GetDateOfContact1Ok returns a tuple with the DateOfContact1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetDateOfContact1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfContact1.Get(), o.DateOfContact1.IsSet()
}

// HasDateOfContact1 returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasDateOfContact1() bool {
	if o != nil && o.DateOfContact1.IsSet() {
		return true
	}

	return false
}

// SetDateOfContact1 gets a reference to the given NullableString and assigns it to the DateOfContact1 field.
func (o *MTOServiceItemDestSIT) SetDateOfContact1(v string) {
	o.DateOfContact1.Set(&v)
}
// SetDateOfContact1Nil sets the value for DateOfContact1 to be an explicit nil
func (o *MTOServiceItemDestSIT) SetDateOfContact1Nil() {
	o.DateOfContact1.Set(nil)
}

// UnsetDateOfContact1 ensures that no value is present for DateOfContact1, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetDateOfContact1() {
	o.DateOfContact1.Unset()
}

// GetDateOfContact2 returns the DateOfContact2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetDateOfContact2() string {
	if o == nil || IsNil(o.DateOfContact2.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfContact2.Get()
}

// GetDateOfContact2Ok returns a tuple with the DateOfContact2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetDateOfContact2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfContact2.Get(), o.DateOfContact2.IsSet()
}

// HasDateOfContact2 returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasDateOfContact2() bool {
	if o != nil && o.DateOfContact2.IsSet() {
		return true
	}

	return false
}

// SetDateOfContact2 gets a reference to the given NullableString and assigns it to the DateOfContact2 field.
func (o *MTOServiceItemDestSIT) SetDateOfContact2(v string) {
	o.DateOfContact2.Set(&v)
}
// SetDateOfContact2Nil sets the value for DateOfContact2 to be an explicit nil
func (o *MTOServiceItemDestSIT) SetDateOfContact2Nil() {
	o.DateOfContact2.Set(nil)
}

// UnsetDateOfContact2 ensures that no value is present for DateOfContact2, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetDateOfContact2() {
	o.DateOfContact2.Unset()
}

// GetTimeMilitary1 returns the TimeMilitary1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetTimeMilitary1() string {
	if o == nil || IsNil(o.TimeMilitary1.Get()) {
		var ret string
		return ret
	}
	return *o.TimeMilitary1.Get()
}

// GetTimeMilitary1Ok returns a tuple with the TimeMilitary1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetTimeMilitary1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeMilitary1.Get(), o.TimeMilitary1.IsSet()
}

// HasTimeMilitary1 returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasTimeMilitary1() bool {
	if o != nil && o.TimeMilitary1.IsSet() {
		return true
	}

	return false
}

// SetTimeMilitary1 gets a reference to the given NullableString and assigns it to the TimeMilitary1 field.
func (o *MTOServiceItemDestSIT) SetTimeMilitary1(v string) {
	o.TimeMilitary1.Set(&v)
}
// SetTimeMilitary1Nil sets the value for TimeMilitary1 to be an explicit nil
func (o *MTOServiceItemDestSIT) SetTimeMilitary1Nil() {
	o.TimeMilitary1.Set(nil)
}

// UnsetTimeMilitary1 ensures that no value is present for TimeMilitary1, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetTimeMilitary1() {
	o.TimeMilitary1.Unset()
}

// GetTimeMilitary2 returns the TimeMilitary2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetTimeMilitary2() string {
	if o == nil || IsNil(o.TimeMilitary2.Get()) {
		var ret string
		return ret
	}
	return *o.TimeMilitary2.Get()
}

// GetTimeMilitary2Ok returns a tuple with the TimeMilitary2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetTimeMilitary2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeMilitary2.Get(), o.TimeMilitary2.IsSet()
}

// HasTimeMilitary2 returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasTimeMilitary2() bool {
	if o != nil && o.TimeMilitary2.IsSet() {
		return true
	}

	return false
}

// SetTimeMilitary2 gets a reference to the given NullableString and assigns it to the TimeMilitary2 field.
func (o *MTOServiceItemDestSIT) SetTimeMilitary2(v string) {
	o.TimeMilitary2.Set(&v)
}
// SetTimeMilitary2Nil sets the value for TimeMilitary2 to be an explicit nil
func (o *MTOServiceItemDestSIT) SetTimeMilitary2Nil() {
	o.TimeMilitary2.Set(nil)
}

// UnsetTimeMilitary2 ensures that no value is present for TimeMilitary2, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetTimeMilitary2() {
	o.TimeMilitary2.Unset()
}

// GetFirstAvailableDeliveryDate1 returns the FirstAvailableDeliveryDate1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetFirstAvailableDeliveryDate1() string {
	if o == nil || IsNil(o.FirstAvailableDeliveryDate1.Get()) {
		var ret string
		return ret
	}
	return *o.FirstAvailableDeliveryDate1.Get()
}

// GetFirstAvailableDeliveryDate1Ok returns a tuple with the FirstAvailableDeliveryDate1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetFirstAvailableDeliveryDate1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstAvailableDeliveryDate1.Get(), o.FirstAvailableDeliveryDate1.IsSet()
}

// HasFirstAvailableDeliveryDate1 returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasFirstAvailableDeliveryDate1() bool {
	if o != nil && o.FirstAvailableDeliveryDate1.IsSet() {
		return true
	}

	return false
}

// SetFirstAvailableDeliveryDate1 gets a reference to the given NullableString and assigns it to the FirstAvailableDeliveryDate1 field.
func (o *MTOServiceItemDestSIT) SetFirstAvailableDeliveryDate1(v string) {
	o.FirstAvailableDeliveryDate1.Set(&v)
}
// SetFirstAvailableDeliveryDate1Nil sets the value for FirstAvailableDeliveryDate1 to be an explicit nil
func (o *MTOServiceItemDestSIT) SetFirstAvailableDeliveryDate1Nil() {
	o.FirstAvailableDeliveryDate1.Set(nil)
}

// UnsetFirstAvailableDeliveryDate1 ensures that no value is present for FirstAvailableDeliveryDate1, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetFirstAvailableDeliveryDate1() {
	o.FirstAvailableDeliveryDate1.Unset()
}

// GetFirstAvailableDeliveryDate2 returns the FirstAvailableDeliveryDate2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetFirstAvailableDeliveryDate2() string {
	if o == nil || IsNil(o.FirstAvailableDeliveryDate2.Get()) {
		var ret string
		return ret
	}
	return *o.FirstAvailableDeliveryDate2.Get()
}

// GetFirstAvailableDeliveryDate2Ok returns a tuple with the FirstAvailableDeliveryDate2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetFirstAvailableDeliveryDate2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstAvailableDeliveryDate2.Get(), o.FirstAvailableDeliveryDate2.IsSet()
}

// HasFirstAvailableDeliveryDate2 returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasFirstAvailableDeliveryDate2() bool {
	if o != nil && o.FirstAvailableDeliveryDate2.IsSet() {
		return true
	}

	return false
}

// SetFirstAvailableDeliveryDate2 gets a reference to the given NullableString and assigns it to the FirstAvailableDeliveryDate2 field.
func (o *MTOServiceItemDestSIT) SetFirstAvailableDeliveryDate2(v string) {
	o.FirstAvailableDeliveryDate2.Set(&v)
}
// SetFirstAvailableDeliveryDate2Nil sets the value for FirstAvailableDeliveryDate2 to be an explicit nil
func (o *MTOServiceItemDestSIT) SetFirstAvailableDeliveryDate2Nil() {
	o.FirstAvailableDeliveryDate2.Set(nil)
}

// UnsetFirstAvailableDeliveryDate2 ensures that no value is present for FirstAvailableDeliveryDate2, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetFirstAvailableDeliveryDate2() {
	o.FirstAvailableDeliveryDate2.Unset()
}

// GetSitEntryDate returns the SitEntryDate field value
func (o *MTOServiceItemDestSIT) GetSitEntryDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SitEntryDate
}

// GetSitEntryDateOk returns a tuple with the SitEntryDate field value
// and a boolean to check if the value has been set.
func (o *MTOServiceItemDestSIT) GetSitEntryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SitEntryDate, true
}

// SetSitEntryDate sets field value
func (o *MTOServiceItemDestSIT) SetSitEntryDate(v string) {
	o.SitEntryDate = v
}

// GetSitDepartureDate returns the SitDepartureDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetSitDepartureDate() string {
	if o == nil || IsNil(o.SitDepartureDate.Get()) {
		var ret string
		return ret
	}
	return *o.SitDepartureDate.Get()
}

// GetSitDepartureDateOk returns a tuple with the SitDepartureDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetSitDepartureDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SitDepartureDate.Get(), o.SitDepartureDate.IsSet()
}

// HasSitDepartureDate returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasSitDepartureDate() bool {
	if o != nil && o.SitDepartureDate.IsSet() {
		return true
	}

	return false
}

// SetSitDepartureDate gets a reference to the given NullableString and assigns it to the SitDepartureDate field.
func (o *MTOServiceItemDestSIT) SetSitDepartureDate(v string) {
	o.SitDepartureDate.Set(&v)
}
// SetSitDepartureDateNil sets the value for SitDepartureDate to be an explicit nil
func (o *MTOServiceItemDestSIT) SetSitDepartureDateNil() {
	o.SitDepartureDate.Set(nil)
}

// UnsetSitDepartureDate ensures that no value is present for SitDepartureDate, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetSitDepartureDate() {
	o.SitDepartureDate.Unset()
}

// GetSitDestinationFinalAddress returns the SitDestinationFinalAddress field value if set, zero value otherwise.
func (o *MTOServiceItemDestSIT) GetSitDestinationFinalAddress() Address {
	if o == nil || IsNil(o.SitDestinationFinalAddress) {
		var ret Address
		return ret
	}
	return *o.SitDestinationFinalAddress
}

// GetSitDestinationFinalAddressOk returns a tuple with the SitDestinationFinalAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MTOServiceItemDestSIT) GetSitDestinationFinalAddressOk() (*Address, bool) {
	if o == nil || IsNil(o.SitDestinationFinalAddress) {
		return nil, false
	}
	return o.SitDestinationFinalAddress, true
}

// HasSitDestinationFinalAddress returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasSitDestinationFinalAddress() bool {
	if o != nil && !IsNil(o.SitDestinationFinalAddress) {
		return true
	}

	return false
}

// SetSitDestinationFinalAddress gets a reference to the given Address and assigns it to the SitDestinationFinalAddress field.
func (o *MTOServiceItemDestSIT) SetSitDestinationFinalAddress(v Address) {
	o.SitDestinationFinalAddress = &v
}

// GetReason returns the Reason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *MTOServiceItemDestSIT) GetReason() string {
	if o == nil || o.Reason.Get() == nil {
		var ret string
		return ret
	}

	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// SetReason sets field value
func (o *MTOServiceItemDestSIT) SetReason(v string) {
	o.Reason.Set(&v)
}

// GetSitAddressUpdates returns the SitAddressUpdates field value if set, zero value otherwise.
func (o *MTOServiceItemDestSIT) GetSitAddressUpdates() []SitAddressUpdate {
	if o == nil || IsNil(o.SitAddressUpdates) {
		var ret []SitAddressUpdate
		return ret
	}
	return o.SitAddressUpdates
}

// GetSitAddressUpdatesOk returns a tuple with the SitAddressUpdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MTOServiceItemDestSIT) GetSitAddressUpdatesOk() ([]SitAddressUpdate, bool) {
	if o == nil || IsNil(o.SitAddressUpdates) {
		return nil, false
	}
	return o.SitAddressUpdates, true
}

// HasSitAddressUpdates returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasSitAddressUpdates() bool {
	if o != nil && !IsNil(o.SitAddressUpdates) {
		return true
	}

	return false
}

// SetSitAddressUpdates gets a reference to the given []SitAddressUpdate and assigns it to the SitAddressUpdates field.
func (o *MTOServiceItemDestSIT) SetSitAddressUpdates(v []SitAddressUpdate) {
	o.SitAddressUpdates = v
}

// GetSitRequestedDelivery returns the SitRequestedDelivery field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetSitRequestedDelivery() string {
	if o == nil || IsNil(o.SitRequestedDelivery.Get()) {
		var ret string
		return ret
	}
	return *o.SitRequestedDelivery.Get()
}

// GetSitRequestedDeliveryOk returns a tuple with the SitRequestedDelivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetSitRequestedDeliveryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SitRequestedDelivery.Get(), o.SitRequestedDelivery.IsSet()
}

// HasSitRequestedDelivery returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasSitRequestedDelivery() bool {
	if o != nil && o.SitRequestedDelivery.IsSet() {
		return true
	}

	return false
}

// SetSitRequestedDelivery gets a reference to the given NullableString and assigns it to the SitRequestedDelivery field.
func (o *MTOServiceItemDestSIT) SetSitRequestedDelivery(v string) {
	o.SitRequestedDelivery.Set(&v)
}
// SetSitRequestedDeliveryNil sets the value for SitRequestedDelivery to be an explicit nil
func (o *MTOServiceItemDestSIT) SetSitRequestedDeliveryNil() {
	o.SitRequestedDelivery.Set(nil)
}

// UnsetSitRequestedDelivery ensures that no value is present for SitRequestedDelivery, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetSitRequestedDelivery() {
	o.SitRequestedDelivery.Unset()
}

// GetSitCustomerContacted returns the SitCustomerContacted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MTOServiceItemDestSIT) GetSitCustomerContacted() string {
	if o == nil || IsNil(o.SitCustomerContacted.Get()) {
		var ret string
		return ret
	}
	return *o.SitCustomerContacted.Get()
}

// GetSitCustomerContactedOk returns a tuple with the SitCustomerContacted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MTOServiceItemDestSIT) GetSitCustomerContactedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SitCustomerContacted.Get(), o.SitCustomerContacted.IsSet()
}

// HasSitCustomerContacted returns a boolean if a field has been set.
func (o *MTOServiceItemDestSIT) HasSitCustomerContacted() bool {
	if o != nil && o.SitCustomerContacted.IsSet() {
		return true
	}

	return false
}

// SetSitCustomerContacted gets a reference to the given NullableString and assigns it to the SitCustomerContacted field.
func (o *MTOServiceItemDestSIT) SetSitCustomerContacted(v string) {
	o.SitCustomerContacted.Set(&v)
}
// SetSitCustomerContactedNil sets the value for SitCustomerContacted to be an explicit nil
func (o *MTOServiceItemDestSIT) SetSitCustomerContactedNil() {
	o.SitCustomerContacted.Set(nil)
}

// UnsetSitCustomerContacted ensures that no value is present for SitCustomerContacted, not even an explicit nil
func (o *MTOServiceItemDestSIT) UnsetSitCustomerContacted() {
	o.SitCustomerContacted.Unset()
}

func (o MTOServiceItemDestSIT) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MTOServiceItemDestSIT) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedMTOServiceItem, errMTOServiceItem := json.Marshal(o.MTOServiceItem)
	if errMTOServiceItem != nil {
		return map[string]interface{}{}, errMTOServiceItem
	}
	errMTOServiceItem = json.Unmarshal([]byte(serializedMTOServiceItem), &toSerialize)
	if errMTOServiceItem != nil {
		return map[string]interface{}{}, errMTOServiceItem
	}
	toSerialize["reServiceCode"] = o.ReServiceCode
	if o.DateOfContact1.IsSet() {
		toSerialize["dateOfContact1"] = o.DateOfContact1.Get()
	}
	if o.DateOfContact2.IsSet() {
		toSerialize["dateOfContact2"] = o.DateOfContact2.Get()
	}
	if o.TimeMilitary1.IsSet() {
		toSerialize["timeMilitary1"] = o.TimeMilitary1.Get()
	}
	if o.TimeMilitary2.IsSet() {
		toSerialize["timeMilitary2"] = o.TimeMilitary2.Get()
	}
	if o.FirstAvailableDeliveryDate1.IsSet() {
		toSerialize["firstAvailableDeliveryDate1"] = o.FirstAvailableDeliveryDate1.Get()
	}
	if o.FirstAvailableDeliveryDate2.IsSet() {
		toSerialize["firstAvailableDeliveryDate2"] = o.FirstAvailableDeliveryDate2.Get()
	}
	toSerialize["sitEntryDate"] = o.SitEntryDate
	if o.SitDepartureDate.IsSet() {
		toSerialize["sitDepartureDate"] = o.SitDepartureDate.Get()
	}
	if !IsNil(o.SitDestinationFinalAddress) {
		toSerialize["sitDestinationFinalAddress"] = o.SitDestinationFinalAddress
	}
	toSerialize["reason"] = o.Reason.Get()
	if !IsNil(o.SitAddressUpdates) {
		toSerialize["sitAddressUpdates"] = o.SitAddressUpdates
	}
	if o.SitRequestedDelivery.IsSet() {
		toSerialize["sitRequestedDelivery"] = o.SitRequestedDelivery.Get()
	}
	if o.SitCustomerContacted.IsSet() {
		toSerialize["sitCustomerContacted"] = o.SitCustomerContacted.Get()
	}
	return toSerialize, nil
}

func (o *MTOServiceItemDestSIT) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reServiceCode",
		"sitEntryDate",
		"reason",
		"moveTaskOrderID",
		"modelType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMTOServiceItemDestSIT := _MTOServiceItemDestSIT{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMTOServiceItemDestSIT)

	if err != nil {
		return err
	}

	*o = MTOServiceItemDestSIT(varMTOServiceItemDestSIT)

	return err
}

type NullableMTOServiceItemDestSIT struct {
	value *MTOServiceItemDestSIT
	isSet bool
}

func (v NullableMTOServiceItemDestSIT) Get() *MTOServiceItemDestSIT {
	return v.value
}

func (v *NullableMTOServiceItemDestSIT) Set(val *MTOServiceItemDestSIT) {
	v.value = val
	v.isSet = true
}

func (v NullableMTOServiceItemDestSIT) IsSet() bool {
	return v.isSet
}

func (v *NullableMTOServiceItemDestSIT) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMTOServiceItemDestSIT(val *MTOServiceItemDestSIT) *NullableMTOServiceItemDestSIT {
	return &NullableMTOServiceItemDestSIT{value: val, isSet: true}
}

func (v NullableMTOServiceItemDestSIT) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMTOServiceItemDestSIT) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


