/*
MilMove Prime V3 API

The Prime V3 API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `/prime/v3/`. 

API version: 0.0.1
Contact: milmove-developers@caci.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MTOServiceItemBasicV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MTOServiceItemBasicV3{}

// MTOServiceItemBasicV3 Describes a basic service item subtype of a MTOServiceItem.
type MTOServiceItemBasicV3 struct {
	MTOServiceItemV3
	ReServiceCode ReServiceCodeV3V3 `json:"reServiceCode"`
}

type _MTOServiceItemBasicV3 MTOServiceItemBasicV3

// NewMTOServiceItemBasicV3 instantiates a new MTOServiceItemBasicV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMTOServiceItemBasicV3(reServiceCode ReServiceCodeV3V3, moveTaskOrderID string, modelType MTOServiceItemModelTypeV3V3) *MTOServiceItemBasicV3 {
	this := MTOServiceItemBasicV3{}
	this.MoveTaskOrderID = moveTaskOrderID
	this.ModelType = modelType
	this.ReServiceCode = reServiceCode
	return &this
}

// NewMTOServiceItemBasicV3WithDefaults instantiates a new MTOServiceItemBasicV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMTOServiceItemBasicV3WithDefaults() *MTOServiceItemBasicV3 {
	this := MTOServiceItemBasicV3{}
	return &this
}

// GetReServiceCode returns the ReServiceCode field value
func (o *MTOServiceItemBasicV3) GetReServiceCode() ReServiceCodeV3V3 {
	if o == nil {
		var ret ReServiceCodeV3V3
		return ret
	}

	return o.ReServiceCode
}

// GetReServiceCodeOk returns a tuple with the ReServiceCode field value
// and a boolean to check if the value has been set.
func (o *MTOServiceItemBasicV3) GetReServiceCodeOk() (*ReServiceCodeV3V3, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReServiceCode, true
}

// SetReServiceCode sets field value
func (o *MTOServiceItemBasicV3) SetReServiceCode(v ReServiceCodeV3V3) {
	o.ReServiceCode = v
}

func (o MTOServiceItemBasicV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MTOServiceItemBasicV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedMTOServiceItemV3, errMTOServiceItemV3 := json.Marshal(o.MTOServiceItemV3)
	if errMTOServiceItemV3 != nil {
		return map[string]interface{}{}, errMTOServiceItemV3
	}
	errMTOServiceItemV3 = json.Unmarshal([]byte(serializedMTOServiceItemV3), &toSerialize)
	if errMTOServiceItemV3 != nil {
		return map[string]interface{}{}, errMTOServiceItemV3
	}
	toSerialize["reServiceCode"] = o.ReServiceCode
	return toSerialize, nil
}

func (o *MTOServiceItemBasicV3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reServiceCode",
		"moveTaskOrderID",
		"modelType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMTOServiceItemBasicV3 := _MTOServiceItemBasicV3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMTOServiceItemBasicV3)

	if err != nil {
		return err
	}

	*o = MTOServiceItemBasicV3(varMTOServiceItemBasicV3)

	return err
}

type NullableMTOServiceItemBasicV3 struct {
	value *MTOServiceItemBasicV3
	isSet bool
}

func (v NullableMTOServiceItemBasicV3) Get() *MTOServiceItemBasicV3 {
	return v.value
}

func (v *NullableMTOServiceItemBasicV3) Set(val *MTOServiceItemBasicV3) {
	v.value = val
	v.isSet = true
}

func (v NullableMTOServiceItemBasicV3) IsSet() bool {
	return v.isSet
}

func (v *NullableMTOServiceItemBasicV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMTOServiceItemBasicV3(val *MTOServiceItemBasicV3) *NullableMTOServiceItemBasicV3 {
	return &NullableMTOServiceItemBasicV3{value: val, isSet: true}
}

func (v NullableMTOServiceItemBasicV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMTOServiceItemBasicV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


