/*
MilMove Prime V2 API

The Prime V2 API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `/prime/v2/`. 

API version: 0.0.1
Contact: milmove-developers@caci.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentServiceItemParamV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentServiceItemParamV2{}

// PaymentServiceItemParamV2 struct for PaymentServiceItemParamV2
type PaymentServiceItemParamV2 struct {
	Id *string `json:"id,omitempty"`
	PaymentServiceItemID *string `json:"paymentServiceItemID,omitempty"`
	Key *ServiceItemParamNameV2V2 `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
	Type *ServiceItemParamTypeV2V2 `json:"type,omitempty"`
	Origin *ServiceItemParamOriginV2V2 `json:"origin,omitempty"`
	ETag *string `json:"eTag,omitempty"`
}

// NewPaymentServiceItemParamV2 instantiates a new PaymentServiceItemParamV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentServiceItemParamV2() *PaymentServiceItemParamV2 {
	this := PaymentServiceItemParamV2{}
	return &this
}

// NewPaymentServiceItemParamV2WithDefaults instantiates a new PaymentServiceItemParamV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentServiceItemParamV2WithDefaults() *PaymentServiceItemParamV2 {
	this := PaymentServiceItemParamV2{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PaymentServiceItemParamV2) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentServiceItemParamV2) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PaymentServiceItemParamV2) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PaymentServiceItemParamV2) SetId(v string) {
	o.Id = &v
}

// GetPaymentServiceItemID returns the PaymentServiceItemID field value if set, zero value otherwise.
func (o *PaymentServiceItemParamV2) GetPaymentServiceItemID() string {
	if o == nil || IsNil(o.PaymentServiceItemID) {
		var ret string
		return ret
	}
	return *o.PaymentServiceItemID
}

// GetPaymentServiceItemIDOk returns a tuple with the PaymentServiceItemID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentServiceItemParamV2) GetPaymentServiceItemIDOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentServiceItemID) {
		return nil, false
	}
	return o.PaymentServiceItemID, true
}

// HasPaymentServiceItemID returns a boolean if a field has been set.
func (o *PaymentServiceItemParamV2) HasPaymentServiceItemID() bool {
	if o != nil && !IsNil(o.PaymentServiceItemID) {
		return true
	}

	return false
}

// SetPaymentServiceItemID gets a reference to the given string and assigns it to the PaymentServiceItemID field.
func (o *PaymentServiceItemParamV2) SetPaymentServiceItemID(v string) {
	o.PaymentServiceItemID = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *PaymentServiceItemParamV2) GetKey() ServiceItemParamNameV2V2 {
	if o == nil || IsNil(o.Key) {
		var ret ServiceItemParamNameV2V2
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentServiceItemParamV2) GetKeyOk() (*ServiceItemParamNameV2V2, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *PaymentServiceItemParamV2) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given ServiceItemParamNameV2V2 and assigns it to the Key field.
func (o *PaymentServiceItemParamV2) SetKey(v ServiceItemParamNameV2V2) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *PaymentServiceItemParamV2) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentServiceItemParamV2) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *PaymentServiceItemParamV2) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *PaymentServiceItemParamV2) SetValue(v string) {
	o.Value = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PaymentServiceItemParamV2) GetType() ServiceItemParamTypeV2V2 {
	if o == nil || IsNil(o.Type) {
		var ret ServiceItemParamTypeV2V2
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentServiceItemParamV2) GetTypeOk() (*ServiceItemParamTypeV2V2, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PaymentServiceItemParamV2) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given ServiceItemParamTypeV2V2 and assigns it to the Type field.
func (o *PaymentServiceItemParamV2) SetType(v ServiceItemParamTypeV2V2) {
	o.Type = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *PaymentServiceItemParamV2) GetOrigin() ServiceItemParamOriginV2V2 {
	if o == nil || IsNil(o.Origin) {
		var ret ServiceItemParamOriginV2V2
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentServiceItemParamV2) GetOriginOk() (*ServiceItemParamOriginV2V2, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *PaymentServiceItemParamV2) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given ServiceItemParamOriginV2V2 and assigns it to the Origin field.
func (o *PaymentServiceItemParamV2) SetOrigin(v ServiceItemParamOriginV2V2) {
	o.Origin = &v
}

// GetETag returns the ETag field value if set, zero value otherwise.
func (o *PaymentServiceItemParamV2) GetETag() string {
	if o == nil || IsNil(o.ETag) {
		var ret string
		return ret
	}
	return *o.ETag
}

// GetETagOk returns a tuple with the ETag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentServiceItemParamV2) GetETagOk() (*string, bool) {
	if o == nil || IsNil(o.ETag) {
		return nil, false
	}
	return o.ETag, true
}

// HasETag returns a boolean if a field has been set.
func (o *PaymentServiceItemParamV2) HasETag() bool {
	if o != nil && !IsNil(o.ETag) {
		return true
	}

	return false
}

// SetETag gets a reference to the given string and assigns it to the ETag field.
func (o *PaymentServiceItemParamV2) SetETag(v string) {
	o.ETag = &v
}

func (o PaymentServiceItemParamV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentServiceItemParamV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PaymentServiceItemID) {
		toSerialize["paymentServiceItemID"] = o.PaymentServiceItemID
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if !IsNil(o.ETag) {
		toSerialize["eTag"] = o.ETag
	}
	return toSerialize, nil
}

type NullablePaymentServiceItemParamV2 struct {
	value *PaymentServiceItemParamV2
	isSet bool
}

func (v NullablePaymentServiceItemParamV2) Get() *PaymentServiceItemParamV2 {
	return v.value
}

func (v *NullablePaymentServiceItemParamV2) Set(val *PaymentServiceItemParamV2) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentServiceItemParamV2) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentServiceItemParamV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentServiceItemParamV2(val *PaymentServiceItemParamV2) *NullablePaymentServiceItemParamV2 {
	return &NullablePaymentServiceItemParamV2{value: val, isSet: true}
}

func (v NullablePaymentServiceItemParamV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentServiceItemParamV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


