/*
MilMove Prime V2 API

The Prime V2 API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `/prime/v2/`. 

API version: 0.0.1
Contact: milmove-developers@caci.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePPMShipmentV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePPMShipmentV2{}

// CreatePPMShipmentV2 Creation object containing the `PPM` shipmentType specific data, not used for other shipment types.
type CreatePPMShipmentV2 struct {
	// Date the customer expects to begin moving from their origin. 
	ExpectedDepartureDate string `json:"expectedDepartureDate"`
	// The address of the origin location where goods are being moved from.
	PickupAddress *AddressV2V2 `json:"pickupAddress,omitempty"`
	// The address of the destination location where goods are being delivered to.
	DestinationAddress *AddressV2V2 `json:"destinationAddress,omitempty"`
	// Captures whether some or all of the PPM shipment will require temporary storage at the origin or destination.  Must be set to `true` when providing `sitLocation`, `sitEstimatedWeight`, `sitEstimatedEntryDate`, and `sitEstimatedDepartureDate` values to calculate the `sitEstimatedCost`. 
	SitExpected bool `json:"sitExpected"`
	SitLocation *SITLocationTypeV2 `json:"sitLocation,omitempty"`
	// The estimated weight of the goods being put into storage in pounds.
	SitEstimatedWeight NullableInt32 `json:"sitEstimatedWeight,omitempty"`
	// The date that goods will first enter the storage location.
	SitEstimatedEntryDate NullableString `json:"sitEstimatedEntryDate,omitempty"`
	// The date that goods will exit the storage location.
	SitEstimatedDepartureDate NullableString `json:"sitEstimatedDepartureDate,omitempty"`
	// The estimated weight of the PPM shipment goods being moved in pounds.
	EstimatedWeight int32 `json:"estimatedWeight"`
	// Indicates whether PPM shipment has pro gear for themselves or their spouse. 
	HasProGear bool `json:"hasProGear"`
	// The estimated weight of the pro-gear being moved belonging to the service member in pounds.
	ProGearWeight NullableInt32 `json:"proGearWeight,omitempty"`
	// The estimated weight of the pro-gear being moved belonging to a spouse in pounds.
	SpouseProGearWeight NullableInt32 `json:"spouseProGearWeight,omitempty"`
}

type _CreatePPMShipmentV2 CreatePPMShipmentV2

// NewCreatePPMShipmentV2 instantiates a new CreatePPMShipmentV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePPMShipmentV2(expectedDepartureDate string, sitExpected bool, estimatedWeight int32, hasProGear bool) *CreatePPMShipmentV2 {
	this := CreatePPMShipmentV2{}
	this.ExpectedDepartureDate = expectedDepartureDate
	this.SitExpected = sitExpected
	this.EstimatedWeight = estimatedWeight
	this.HasProGear = hasProGear
	return &this
}

// NewCreatePPMShipmentV2WithDefaults instantiates a new CreatePPMShipmentV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePPMShipmentV2WithDefaults() *CreatePPMShipmentV2 {
	this := CreatePPMShipmentV2{}
	return &this
}

// GetExpectedDepartureDate returns the ExpectedDepartureDate field value
func (o *CreatePPMShipmentV2) GetExpectedDepartureDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedDepartureDate
}

// GetExpectedDepartureDateOk returns a tuple with the ExpectedDepartureDate field value
// and a boolean to check if the value has been set.
func (o *CreatePPMShipmentV2) GetExpectedDepartureDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedDepartureDate, true
}

// SetExpectedDepartureDate sets field value
func (o *CreatePPMShipmentV2) SetExpectedDepartureDate(v string) {
	o.ExpectedDepartureDate = v
}

// GetPickupAddress returns the PickupAddress field value if set, zero value otherwise.
func (o *CreatePPMShipmentV2) GetPickupAddress() AddressV2V2 {
	if o == nil || IsNil(o.PickupAddress) {
		var ret AddressV2V2
		return ret
	}
	return *o.PickupAddress
}

// GetPickupAddressOk returns a tuple with the PickupAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePPMShipmentV2) GetPickupAddressOk() (*AddressV2V2, bool) {
	if o == nil || IsNil(o.PickupAddress) {
		return nil, false
	}
	return o.PickupAddress, true
}

// HasPickupAddress returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasPickupAddress() bool {
	if o != nil && !IsNil(o.PickupAddress) {
		return true
	}

	return false
}

// SetPickupAddress gets a reference to the given AddressV2V2 and assigns it to the PickupAddress field.
func (o *CreatePPMShipmentV2) SetPickupAddress(v AddressV2V2) {
	o.PickupAddress = &v
}

// GetDestinationAddress returns the DestinationAddress field value if set, zero value otherwise.
func (o *CreatePPMShipmentV2) GetDestinationAddress() AddressV2V2 {
	if o == nil || IsNil(o.DestinationAddress) {
		var ret AddressV2V2
		return ret
	}
	return *o.DestinationAddress
}

// GetDestinationAddressOk returns a tuple with the DestinationAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePPMShipmentV2) GetDestinationAddressOk() (*AddressV2V2, bool) {
	if o == nil || IsNil(o.DestinationAddress) {
		return nil, false
	}
	return o.DestinationAddress, true
}

// HasDestinationAddress returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasDestinationAddress() bool {
	if o != nil && !IsNil(o.DestinationAddress) {
		return true
	}

	return false
}

// SetDestinationAddress gets a reference to the given AddressV2V2 and assigns it to the DestinationAddress field.
func (o *CreatePPMShipmentV2) SetDestinationAddress(v AddressV2V2) {
	o.DestinationAddress = &v
}

// GetSitExpected returns the SitExpected field value
func (o *CreatePPMShipmentV2) GetSitExpected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SitExpected
}

// GetSitExpectedOk returns a tuple with the SitExpected field value
// and a boolean to check if the value has been set.
func (o *CreatePPMShipmentV2) GetSitExpectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SitExpected, true
}

// SetSitExpected sets field value
func (o *CreatePPMShipmentV2) SetSitExpected(v bool) {
	o.SitExpected = v
}

// GetSitLocation returns the SitLocation field value if set, zero value otherwise.
func (o *CreatePPMShipmentV2) GetSitLocation() SITLocationTypeV2 {
	if o == nil || IsNil(o.SitLocation) {
		var ret SITLocationTypeV2
		return ret
	}
	return *o.SitLocation
}

// GetSitLocationOk returns a tuple with the SitLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePPMShipmentV2) GetSitLocationOk() (*SITLocationTypeV2, bool) {
	if o == nil || IsNil(o.SitLocation) {
		return nil, false
	}
	return o.SitLocation, true
}

// HasSitLocation returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasSitLocation() bool {
	if o != nil && !IsNil(o.SitLocation) {
		return true
	}

	return false
}

// SetSitLocation gets a reference to the given SITLocationTypeV2 and assigns it to the SitLocation field.
func (o *CreatePPMShipmentV2) SetSitLocation(v SITLocationTypeV2) {
	o.SitLocation = &v
}

// GetSitEstimatedWeight returns the SitEstimatedWeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePPMShipmentV2) GetSitEstimatedWeight() int32 {
	if o == nil || IsNil(o.SitEstimatedWeight.Get()) {
		var ret int32
		return ret
	}
	return *o.SitEstimatedWeight.Get()
}

// GetSitEstimatedWeightOk returns a tuple with the SitEstimatedWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePPMShipmentV2) GetSitEstimatedWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SitEstimatedWeight.Get(), o.SitEstimatedWeight.IsSet()
}

// HasSitEstimatedWeight returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasSitEstimatedWeight() bool {
	if o != nil && o.SitEstimatedWeight.IsSet() {
		return true
	}

	return false
}

// SetSitEstimatedWeight gets a reference to the given NullableInt32 and assigns it to the SitEstimatedWeight field.
func (o *CreatePPMShipmentV2) SetSitEstimatedWeight(v int32) {
	o.SitEstimatedWeight.Set(&v)
}
// SetSitEstimatedWeightNil sets the value for SitEstimatedWeight to be an explicit nil
func (o *CreatePPMShipmentV2) SetSitEstimatedWeightNil() {
	o.SitEstimatedWeight.Set(nil)
}

// UnsetSitEstimatedWeight ensures that no value is present for SitEstimatedWeight, not even an explicit nil
func (o *CreatePPMShipmentV2) UnsetSitEstimatedWeight() {
	o.SitEstimatedWeight.Unset()
}

// GetSitEstimatedEntryDate returns the SitEstimatedEntryDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePPMShipmentV2) GetSitEstimatedEntryDate() string {
	if o == nil || IsNil(o.SitEstimatedEntryDate.Get()) {
		var ret string
		return ret
	}
	return *o.SitEstimatedEntryDate.Get()
}

// GetSitEstimatedEntryDateOk returns a tuple with the SitEstimatedEntryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePPMShipmentV2) GetSitEstimatedEntryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SitEstimatedEntryDate.Get(), o.SitEstimatedEntryDate.IsSet()
}

// HasSitEstimatedEntryDate returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasSitEstimatedEntryDate() bool {
	if o != nil && o.SitEstimatedEntryDate.IsSet() {
		return true
	}

	return false
}

// SetSitEstimatedEntryDate gets a reference to the given NullableString and assigns it to the SitEstimatedEntryDate field.
func (o *CreatePPMShipmentV2) SetSitEstimatedEntryDate(v string) {
	o.SitEstimatedEntryDate.Set(&v)
}
// SetSitEstimatedEntryDateNil sets the value for SitEstimatedEntryDate to be an explicit nil
func (o *CreatePPMShipmentV2) SetSitEstimatedEntryDateNil() {
	o.SitEstimatedEntryDate.Set(nil)
}

// UnsetSitEstimatedEntryDate ensures that no value is present for SitEstimatedEntryDate, not even an explicit nil
func (o *CreatePPMShipmentV2) UnsetSitEstimatedEntryDate() {
	o.SitEstimatedEntryDate.Unset()
}

// GetSitEstimatedDepartureDate returns the SitEstimatedDepartureDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePPMShipmentV2) GetSitEstimatedDepartureDate() string {
	if o == nil || IsNil(o.SitEstimatedDepartureDate.Get()) {
		var ret string
		return ret
	}
	return *o.SitEstimatedDepartureDate.Get()
}

// GetSitEstimatedDepartureDateOk returns a tuple with the SitEstimatedDepartureDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePPMShipmentV2) GetSitEstimatedDepartureDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SitEstimatedDepartureDate.Get(), o.SitEstimatedDepartureDate.IsSet()
}

// HasSitEstimatedDepartureDate returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasSitEstimatedDepartureDate() bool {
	if o != nil && o.SitEstimatedDepartureDate.IsSet() {
		return true
	}

	return false
}

// SetSitEstimatedDepartureDate gets a reference to the given NullableString and assigns it to the SitEstimatedDepartureDate field.
func (o *CreatePPMShipmentV2) SetSitEstimatedDepartureDate(v string) {
	o.SitEstimatedDepartureDate.Set(&v)
}
// SetSitEstimatedDepartureDateNil sets the value for SitEstimatedDepartureDate to be an explicit nil
func (o *CreatePPMShipmentV2) SetSitEstimatedDepartureDateNil() {
	o.SitEstimatedDepartureDate.Set(nil)
}

// UnsetSitEstimatedDepartureDate ensures that no value is present for SitEstimatedDepartureDate, not even an explicit nil
func (o *CreatePPMShipmentV2) UnsetSitEstimatedDepartureDate() {
	o.SitEstimatedDepartureDate.Unset()
}

// GetEstimatedWeight returns the EstimatedWeight field value
func (o *CreatePPMShipmentV2) GetEstimatedWeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EstimatedWeight
}

// GetEstimatedWeightOk returns a tuple with the EstimatedWeight field value
// and a boolean to check if the value has been set.
func (o *CreatePPMShipmentV2) GetEstimatedWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EstimatedWeight, true
}

// SetEstimatedWeight sets field value
func (o *CreatePPMShipmentV2) SetEstimatedWeight(v int32) {
	o.EstimatedWeight = v
}

// GetHasProGear returns the HasProGear field value
func (o *CreatePPMShipmentV2) GetHasProGear() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasProGear
}

// GetHasProGearOk returns a tuple with the HasProGear field value
// and a boolean to check if the value has been set.
func (o *CreatePPMShipmentV2) GetHasProGearOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasProGear, true
}

// SetHasProGear sets field value
func (o *CreatePPMShipmentV2) SetHasProGear(v bool) {
	o.HasProGear = v
}

// GetProGearWeight returns the ProGearWeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePPMShipmentV2) GetProGearWeight() int32 {
	if o == nil || IsNil(o.ProGearWeight.Get()) {
		var ret int32
		return ret
	}
	return *o.ProGearWeight.Get()
}

// GetProGearWeightOk returns a tuple with the ProGearWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePPMShipmentV2) GetProGearWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProGearWeight.Get(), o.ProGearWeight.IsSet()
}

// HasProGearWeight returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasProGearWeight() bool {
	if o != nil && o.ProGearWeight.IsSet() {
		return true
	}

	return false
}

// SetProGearWeight gets a reference to the given NullableInt32 and assigns it to the ProGearWeight field.
func (o *CreatePPMShipmentV2) SetProGearWeight(v int32) {
	o.ProGearWeight.Set(&v)
}
// SetProGearWeightNil sets the value for ProGearWeight to be an explicit nil
func (o *CreatePPMShipmentV2) SetProGearWeightNil() {
	o.ProGearWeight.Set(nil)
}

// UnsetProGearWeight ensures that no value is present for ProGearWeight, not even an explicit nil
func (o *CreatePPMShipmentV2) UnsetProGearWeight() {
	o.ProGearWeight.Unset()
}

// GetSpouseProGearWeight returns the SpouseProGearWeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePPMShipmentV2) GetSpouseProGearWeight() int32 {
	if o == nil || IsNil(o.SpouseProGearWeight.Get()) {
		var ret int32
		return ret
	}
	return *o.SpouseProGearWeight.Get()
}

// GetSpouseProGearWeightOk returns a tuple with the SpouseProGearWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePPMShipmentV2) GetSpouseProGearWeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpouseProGearWeight.Get(), o.SpouseProGearWeight.IsSet()
}

// HasSpouseProGearWeight returns a boolean if a field has been set.
func (o *CreatePPMShipmentV2) HasSpouseProGearWeight() bool {
	if o != nil && o.SpouseProGearWeight.IsSet() {
		return true
	}

	return false
}

// SetSpouseProGearWeight gets a reference to the given NullableInt32 and assigns it to the SpouseProGearWeight field.
func (o *CreatePPMShipmentV2) SetSpouseProGearWeight(v int32) {
	o.SpouseProGearWeight.Set(&v)
}
// SetSpouseProGearWeightNil sets the value for SpouseProGearWeight to be an explicit nil
func (o *CreatePPMShipmentV2) SetSpouseProGearWeightNil() {
	o.SpouseProGearWeight.Set(nil)
}

// UnsetSpouseProGearWeight ensures that no value is present for SpouseProGearWeight, not even an explicit nil
func (o *CreatePPMShipmentV2) UnsetSpouseProGearWeight() {
	o.SpouseProGearWeight.Unset()
}

func (o CreatePPMShipmentV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePPMShipmentV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expectedDepartureDate"] = o.ExpectedDepartureDate
	if !IsNil(o.PickupAddress) {
		toSerialize["pickupAddress"] = o.PickupAddress
	}
	if !IsNil(o.DestinationAddress) {
		toSerialize["destinationAddress"] = o.DestinationAddress
	}
	toSerialize["sitExpected"] = o.SitExpected
	if !IsNil(o.SitLocation) {
		toSerialize["sitLocation"] = o.SitLocation
	}
	if o.SitEstimatedWeight.IsSet() {
		toSerialize["sitEstimatedWeight"] = o.SitEstimatedWeight.Get()
	}
	if o.SitEstimatedEntryDate.IsSet() {
		toSerialize["sitEstimatedEntryDate"] = o.SitEstimatedEntryDate.Get()
	}
	if o.SitEstimatedDepartureDate.IsSet() {
		toSerialize["sitEstimatedDepartureDate"] = o.SitEstimatedDepartureDate.Get()
	}
	toSerialize["estimatedWeight"] = o.EstimatedWeight
	toSerialize["hasProGear"] = o.HasProGear
	if o.ProGearWeight.IsSet() {
		toSerialize["proGearWeight"] = o.ProGearWeight.Get()
	}
	if o.SpouseProGearWeight.IsSet() {
		toSerialize["spouseProGearWeight"] = o.SpouseProGearWeight.Get()
	}
	return toSerialize, nil
}

func (o *CreatePPMShipmentV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expectedDepartureDate",
		"sitExpected",
		"estimatedWeight",
		"hasProGear",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePPMShipmentV2 := _CreatePPMShipmentV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePPMShipmentV2)

	if err != nil {
		return err
	}

	*o = CreatePPMShipmentV2(varCreatePPMShipmentV2)

	return err
}

type NullableCreatePPMShipmentV2 struct {
	value *CreatePPMShipmentV2
	isSet bool
}

func (v NullableCreatePPMShipmentV2) Get() *CreatePPMShipmentV2 {
	return v.value
}

func (v *NullableCreatePPMShipmentV2) Set(val *CreatePPMShipmentV2) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePPMShipmentV2) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePPMShipmentV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePPMShipmentV2(val *CreatePPMShipmentV2) *NullableCreatePPMShipmentV2 {
	return &NullableCreatePPMShipmentV2{value: val, isSet: true}
}

func (v NullableCreatePPMShipmentV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePPMShipmentV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


