=begin
#MilMove Prime V3 API

#The Prime V3 API is a RESTful API that enables the Prime contractor to request information about upcoming moves, update the details and status of those moves, and make payment requests. It uses Mutual TLS for authentication procedures.  All endpoints are located at `/prime/v3/`. 

The version of the OpenAPI document: 0.0.1
Contact: milmove-developers@caci.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::MoveTaskOrderApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MoveTaskOrderApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::MoveTaskOrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MoveTaskOrderApi' do
    it 'should create an instance of MoveTaskOrderApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::MoveTaskOrderApi)
    end
  end

  # unit tests for get_move_task_order
  # getMoveTaskOrder
  # ### Functionality This endpoint gets an individual MoveTaskOrder by ID.  It will provide information about the Customer and any associated MTOShipments, MTOServiceItems and PaymentRequests. 
  # @param move_id UUID or MoveCode of move task order to use........
  # @param [Hash] opts the optional parameters
  # @return [MoveTaskOrder]
  describe 'get_move_task_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
